# Basis #

Cash flow replication. Let's consider cash flows over 3 periods, given by 3-vectors below

\begin{align}
e_1 = \begin{bmatrix}
    1 \\
    0 \\
    0
\end{bmatrix}, 
\space\space\space

l_1 = \begin{bmatrix}
    1 \\
    -(1+r) \\
    0
\end{bmatrix},
\space\space\space

l_2 = \begin{bmatrix}
    0 \\
    1 \\
    -(1+r)
\end{bmatrix}
\space\space\space


\end{align}

form a basis, where r is the (positive) per-period interest rate. The first vector e1 is a single payment of $1 in period (time) t = 1. The second vector l1 is loan of $1 in period t = 1, paid back in period t = 2 with interest r. The third vector l2 is loan of $1 in period t = 2, paid back in period t = 3 with interest r. 

Let’s use this basis to replicate the cash flow c = (1, 2, −3) as

\begin{align}
    c = \alpha_1e_1 + \alpha_2l_1+\alpha_3l_2 =
    \alpha_1\begin{bmatrix}
        1 \\
        0 \\
        0
    \end{bmatrix} 
    +
    \alpha_2\begin{bmatrix}
        1 \\
        -(1+r) \\
        0
    \end{bmatrix}
    +
    \alpha_3\begin{bmatrix}
        0 \\
        1 \\
        -(1+r)
    \end{bmatrix}
\end{align}

In [8]:
uv(i, n) = [zeros(i-1); 1; zeros(n-i)]
e1 = uv(1, 3)
r = 0.05
l1 = [1; -(1+r); 0]
l2 = [0; 1; -(1+r)]
c = [1; 2; -3]
alpha3 = -c[3]/(1+r)
alpha2 = -c[2]/(1+r)-c[3]/(1+r)^2
alpha1 = c[1] + c[2]/(1+r)+c[3]/(1+r)^2
alpha1*e1+alpha2*l1+alpha3*l2

3-element Vector{Float64}:
  1.0
  2.0
 -3.0

## Orthonomal vectors
### Expansion in an orthonomal basis.

Let's check that the vectors

\begin{align}
    a_1 = \begin{bmatrix}
        0 \\
        0 \\
        -1
    \end{bmatrix} 
    \space\space\space
    a_2 = \frac{1}{\sqrt{2}}\begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix}
    \space\space\space
    a_3 = \frac{1}{\sqrt{2}}\begin{bmatrix}
        1 \\
        -1 \\
        0
    \end{bmatrix}
\end{align}

form an orthonormal basis, check the expansion of x = (1, 2, 3) in this basis

$ x = (a^T_1x)a_1 + ... + (a^T_nx)a_n$

In [15]:
using LinearAlgebra
a1 = [0, 0, -1]
a2 = 1/sqrt(2) * [1; 1; 0]
a3 = 1/sqrt(2) * [1; -1; 0]

# check if 3 vectors a1, a2, a3 form an orthonormal basis
dot(a1, a2), dot(a1, a3), dot(a2, a3), norm(a1), norm(a2), norm(a3)

(0.0, 0.0, -2.2371143170757382e-17, 1.0, 0.9999999999999999, 0.9999999999999999)

In [16]:
x = [1, 2, 3]
# beta1 is the first coefficient of the expansion of x in the basis {a1, a2, a3}
beta1 = dot(a1, x)
beta2 = dot(a2, x)
beta3 = dot(a3, x)

xexp = beta1 * a1 + beta2 * a2 + beta3 * a3

3-element Vector{Float64}:
 0.9999999999999999
 1.9999999999999996
 3.0

# Gram Schmidt Algorithm
Given input an array [a[1], a[2], ..., a[k]], containing the k vectors a1, ..., ak.

if a1, ..., ak are linearly indepndent, it returns an array of orthonormal vectors[q[1], ..., q[k]]

If a1, ..., ak are linearly dependent, the algorithm terminates early in iteration i, and returns the array [q[1], ..., q[i]]
of length i

In [22]:
function gram_schmidt(a; tol = 1e-10)
    q = []
    for i = 1:length(a)
        qtilde = a[i]
        for j =1:i-1
            qtilde -= dot(q[j], a[i])*q[j]
        end
        if norm(qtilde) < tol 
            println(a, " is linearly dependent")
            return q
        end
        qi = qtilde/norm(qtilde)
        push!(q, qi)
    end
    return q
end

gram_schmidt (generic function with 1 method)

In [23]:
a = [
        [-1, 1, -1, 1], 
        [-1, 3, -1, 3], 
        [1, 3, 5, 7] ]
gram_schmidt(a)

3-element Vector{Any}:
 [-0.5, 0.5, -0.5, 0.5]
 [0.5, 0.5, 0.5, 0.5]
 [-0.5, -0.5, 0.5, 0.5]

In [27]:
b = [[1, 1], [1, 2], [-1, 1]]
q = gram_schmidt(b)

# check  if q1, q2 are orthonormal vectors
dot(q[1], q[2]), norm(q[1]), norm(q[2])

[[1, 1], [1, 2], [-1, 1]] is linearly dependent


(4.799296168983549e-16, 0.9999999999999999, 0.9999999999999999)