In [28]:
using LinearAlgebra
A = [0 1 -2.3 0.1; 
     1.3 4 -0.1 0; 
     4.1 -1 0 1.7]
size(A), size(A, 1), size(A, 2)
m, n = size(A)

println(n)

tall(X) = size(X, 1) > size(X, 2)
tall(A)
using Printf
@printf("is A a tall matrix? %s", tall(A))

4
is A a tall matrix? false

In [28]:
B = copy(A)
B[2, 2] = 0
print(A == B)
C = A .== B
C
sum(C)

false

11

In [30]:
A = [-2.1 3 0]
B = [-2.1; 3; 0]

3-element Vector{Float64}:
 -2.1
  3.0
  0.0

In [4]:
A = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]
# I22 = A[1:2, 3:end]

I22 = A[1:2, 3:4]

#Third column of A
A3 = A[:, 3]


3-element Vector{Int64}:
  1
  0
 -2

In [5]:
B = [ 1 -3 ; 2 0 ; 1 -2]

3×2 Matrix{Int64}:
 1  -3
 2   0
 1  -2

In [6]:
B[:]

6-element Vector{Int64}:
  1
  2
  1
 -3
  0
 -2

In [ ]:
B = [0 2 3];
C = [-1];
D = [2 2 1 ; 1 3 5];
E = [4; 4];
A = [B C ; D E]

In [7]:
reshape(B, (2, 3))

2×3 Matrix{Int64}:
 1   1   0
 2  -3  -2

In [9]:
a = [ [1., 2.], [4., 5.], [7., 8.] ]
A = hcat(a...)

2×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0

In [13]:
eye(n) = 1.0*Matrix(I, n, n)

eye (generic function with 1 method)

In [14]:
eye(4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [16]:
A = [1 -1 2; 0 3 -1]

2×3 Matrix{Int64}:
 1  -1   2
 0   3  -1

In [18]:
[A I]

2×5 Matrix{Int64}:
 1  -1   2  1  0
 0   3  -1  0  1

In [20]:
[A; I]

5×3 Matrix{Int64}:
 1  -1   2
 0   3  -1
 1   0   0
 0   1   0
 0   0   1

In [21]:
diagm([1, 2, 3])

3×3 Matrix{Int64}:
 1  0  0
 0  2  0
 0  0  3

In [23]:
H = [0 1 -2 1; 2 -1 3 0]

2×4 Matrix{Int64}:
 0   1  -2  1
 2  -1   3  0

In [24]:
diag(H)

2-element Vector{Int64}:
  0
 -1

In [25]:
rand(2,3)

2×3 Matrix{Float64}:
 0.358969    0.935449  0.543567
 0.00571138  0.42439   0.589996

In [26]:
randn(3,2)

3×2 Matrix{Float64}:
 -0.324431  -1.0349
  0.428124  -0.21439
 -0.141738  -0.25175

In [30]:
using SparseArrays
rowind = [ 1, 2, 2, 1, 3, 4 ];
colind = [ 1, 1, 2, 3, 3, 4 ];
values = [-1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ];
A = sparse(rowind, colind, values, 4, 5)

4×5 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -1.11    ⋅    1.17   ⋅     ⋅ 
  0.15  -0.1    ⋅     ⋅     ⋅ 
   ⋅      ⋅   -0.3    ⋅     ⋅ 
   ⋅      ⋅     ⋅    0.13   ⋅ 

In [31]:
nnz(A)

6

In [33]:
A = sparse([1, 3, 2, 1], [1, 1, 2, 3],
   [1.0, 2.0, 3.0, 4.0], 3, 3)

3×3 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅   4.0
  ⋅   3.0   ⋅ 
 2.0   ⋅    ⋅ 

In [34]:
B = Array(A)

3×3 Matrix{Float64}:
 1.0  0.0  4.0
 0.0  3.0  0.0
 2.0  0.0  0.0

In [35]:
B[1,3] = 0.0;

In [36]:
sparse(B)

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   3.0   ⋅ 
 2.0   ⋅    ⋅ 

In [38]:
speye(n) = sparse(1.0I, n , n)

speye (generic function with 1 method)

In [39]:
speye(4)

4×4 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [44]:
spdiagm(x) = sparse([1:length(x);], [1:length(x);], x, length(x), length(x))

spdiagm (generic function with 1 method)

In [45]:
spdiagm([1, 2, 3, 4])

4×4 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 1  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅
 ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  4

In [51]:
A = sprand(10, 10, 0.01)

10×10 SparseMatrixCSC{Float64, Int64} with 2 stored entries:
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.855057   ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅    ⋅         ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅         ⋅    ⋅    ⋅   0.915034   ⋅    ⋅    ⋅    ⋅ 

In [53]:
A = sprandn(10, 10, 0.01)

10×10 SparseMatrixCSC{Float64, Int64} with 1 stored entry:
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
 0.159757   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅         ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 

# Transpose

In [64]:
H = [0 1 -2 1; 2 -1 3 0]
exp.(H)

2×4 Matrix{Float64}:
 1.0      2.71828    0.135335  2.71828
 7.38906  0.367879  20.0855    1.0

In [55]:
HT = H'

4×2 adjoint(::Matrix{Int64}) with eltype Int64:
  0   2
  1  -1
 -2   3
  1   0

In [56]:
U = [ 0 4; 7 0; 3 1]

3×2 Matrix{Int64}:
 0  4
 7  0
 3  1

In [57]:
V = [ 1 2; 2 3; 0 4]

3×2 Matrix{Int64}:
 1  2
 2  3
 0  4

In [58]:
U+V

3×2 Matrix{Int64}:
 1  6
 9  3
 3  5

In [59]:
2.2*U

3×2 Matrix{Float64}:
  0.0  8.8
 15.4  0.0
  6.6  2.2

In [66]:
A = [2 3 -1; 0 1 4]
norm(A)

5.5677643628300215

In [68]:
A[:]

6-element Vector{Int64}:
  2
  0
  3
  1
 -1
  4

In [67]:
norm(A[:])

5.5677643628300215

In [80]:
difference_matrix(n) = [-eye(n-1) spzeros(n-1)] + [zeros(n-1) eye(n-1)];
D = difference_matrix(6)

5×6 Matrix{Float64}:
 -1.0   1.0   0.0   0.0   0.0  0.0
  0.0  -1.0   1.0   0.0   0.0  0.0
  0.0   0.0  -1.0   1.0   0.0  0.0
  0.0   0.0   0.0  -1.0   1.0  0.0
  0.0   0.0   0.0   0.0  -1.0  1.0

In [71]:
D*[-1, 0, 2, 1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

In [72]:
difference_matrix(n) = [-speye(n-1) spzeros(n-1)] +
[spzeros(n-1) speye(n-1)];
D = difference_matrix(4)

3×4 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -1.0   1.0    ⋅    ⋅ 
   ⋅   -1.0   1.0   ⋅ 
   ⋅     ⋅   -1.0  1.0

In [73]:
D*[-1, 0, 2, 1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

In [81]:
function running_sum(n)
    S = zeros(n, n)
    for i = 1:n
        for j = 1:i
            S[i, j] = 1
        end
    end
    return S 
end



running_sum (generic function with 1 method)

In [82]:
running_sum(4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

In [83]:
running_sum(4) * [-1, 1, 2, 0]

4-element Vector{Float64}:
 -1.0
  0.0
  2.0
  2.0

In [86]:
runningsum(n) = tril(ones(n, n))

runningsum (generic function with 1 method)

In [88]:
runningsum(7)

7×7 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [89]:
vandermonde(t, n) = hcat([t.^i for i = 0:n-1]...)
t = [1, 2, 3, 4, 5]
vandermonde(t, 5)

5×5 Matrix{Int64}:
 1  1   1    1    1
 1  2   4    8   16
 1  3   9   27   81
 1  4  16   64  256
 1  5  25  125  625

In [91]:
A = rand(1000, 10000); x = rand(10000)
@time y = A*x 

  0.007818 seconds (4.33 k allocations: 310.367 KiB, 50.70% compilation time)


1000-element Vector{Float64}:
 2540.761934147786
 2541.2623956405987
 2578.683241967469
 2515.5521639571234
 2563.1480132742745
 2540.100882417197
 2542.8421934086555
 2535.99618492108
 2547.7004994216413
 2532.370411140783
    ⋮
 2536.78485309826
 2538.9771366940267
 2553.7809152689433
 2539.7523374264524
 2539.478397318244
 2575.989035591748
 2540.1615662949034
 2543.5389623524266
 2544.7278794369195

In [92]:
@time y = A*x 

  0.002603 seconds (1 allocation: 8.000 KiB)


1000-element Vector{Float64}:
 2540.761934147786
 2541.2623956405987
 2578.683241967469
 2515.5521639571234
 2563.1480132742745
 2540.100882417197
 2542.8421934086555
 2535.99618492108
 2547.7004994216413
 2532.370411140783
    ⋮
 2536.78485309826
 2538.9771366940267
 2553.7809152689433
 2539.7523374264524
 2539.478397318244
 2575.989035591748
 2540.1615662949034
 2543.5389623524266
 2544.7278794369195

In [102]:
A = rand(5000, 20000)
x = rand(20000)
@time A*x

  0.017923 seconds (2 allocations: 39.172 KiB)


5000-element Vector{Float64}:
 4971.776040381644
 5004.374611706031
 4964.598511040578
 5002.86820578391
 4989.618022811389
 4982.000234892878
 4993.889999341054
 4976.002062923415
 5000.227907336537
 5036.497182407499
    ⋮
 4974.210591124289
 4984.897143140432
 4970.042814937862
 5012.972266441028
 4987.029692007548
 5010.6674611950075
 5021.854728649605
 4996.699579664277
 5007.722508024485

In [ ]:
n = 10^4
D = difference(4)